spring.application.name=agents_service_with_jpa

spring.datasource.url=jdbc:h2:file:./data/testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.h2.console.enabled=true
spring.jpa.show-sql=true


management.endpoints.web.exposure.include=*

management.info.env.enabled=true

info.app.name=${spring.application.name}
info.build.artificatId= '@project.artifact@'
info.build.groupId='@project.groupId@'
info.java.version= '@java.version@'

